### ISSUE TITLE
Inline import CSS bug 

### ISSUE THREAD

**Issue by Sylwekqaz** [sp00m/gulp-watch-sass#3]
I have inline import `.css` file  (`main-style.css`) in my `.scss` file like 
```@import "../main-style"; ```
and sass compiles without errors, but watch task throws info about missing file 
```Could not resolve '../main-style' from file 'C:\patch\to\file\style.scss': file not found```, and watch not work on `.css` files

**Comment by sp00m** [comment]
Thanks for raising it, I'll investigate.

**Comment by sp00m** [comment]
@Sylwekqaz The `@import` statement will be fixed, but you still won't be able to watch for CSS files changes. Why would you like to watch for CSS files changes actually? Because if it's a file within your codebase, then you should probably convert it into a SCSS file, and if it's a file from an external library, then it should not change, am I wrong?

**Comment by Sylwekqaz** [comment]
Theoretically: you are right (maybe its will be use full on changing external library version, but its rare use case)
Practically: sometimes bad things happen in projects, and there no time (money) to fix it.

**Comment by sp00m** [comment]
OK, I'll see what I can do. BTW, in the meantime, you can probably just rename your file from `.css` to `.scss` as [SCSS is a superset of CSS](http://sass-lang.com/documentation/):

> Every valid CSS stylesheet is valid SCSS as well.

Keep you posted soon!

**Comment by Sylwekqaz** [comment]
Yes I know, and meantime I use this workaround before I fix problem in our
project.

Thanks

W dniu śr., 26.07.2017 o 15:52 Christophe Maillard <notifications@github.com>
napisał(a):

**Comment by sp00m** [comment]
This has been fixed in version 1.2.0 (you can now watch for CSS files modifications in addition to SASS ones).
