### ISSUE TITLE
How to prevent break when sass error ?

### ISSUE THREAD

**Issue by kytosai** [sp00m/gulp-watch-sass#5]
I have use gulp-watch-sass but when i typing error in scss and build gulp is gulp task auto finish :( !!

http://prntscr.com/h0ulgz

i try use plumber plugin but cannot resume task

http://prntscr.com/h0um2d

It cannot resume when error 

Sorry, i'm not good english ! :( 
Can you help me ?

**Comment by sp00m** [comment]
Weird, I've been using it with `plumber`successfully personally. Could you post your actual code (instead of images), plus the versions of Node, NPM and Gulp you're using, so that I can try to replicate locally?

**Comment by kytosai** [comment]
I have found a way to run continuously 

Old: http://prntscr.com/h0ylr5

New: http://prntscr.com/h0ykya

I changed **sass.logError** to **function** and content **console.log(error)**
Thank you !! :) 

UPdate: sorry but it cannot work good :(  !!!
