### ISSUE TITLE
How to get list file to build scss in watchSass !!!???

### ISSUE THREAD

**Issue by kytosai** [sp00m/gulp-watch-sass#7]
I want go get list main scss file to build css file from watchSass (file *.scss not _*.scss)
I try consolog from callback in watchSass but it only return file i'm editing !

**Comment by sp00m** [comment]
I don't understand your point. Have you looked at the [Usage section](https://github.com/sp00m/gulp-watch-sass#usage)? What's not working?

Also, one question mark would probably have sufficed in the question title.

**Comment by sp00m** [comment]
Closing as unclear and unanswered.
