### ISSUE TITLE
Sass partial change doesn't triggered to recompile main sass file

### ISSUE THREAD

**Issue by kolyaraketa** [sp00m/gulp-watch-sass#8]
When I changing a file `_base.sass`, nothing happens, what am I doing wrong?
```
gulp.task("sassp", () => watchSass(['./src/sass/**/*.sass'])
  .pipe(sass())
  .pipe(gulp.dest("./public")));
```

![image](https://user-images.githubusercontent.com/14001747/34318966-4efbf9a8-e7dd-11e7-9d29-c5935268554f.png)

**Comment by sp00m** [comment]
Would you be able to provide an [MVCE](https://stackoverflow.com/help/mcve) so that I can try to reproduce the issue you're facing? Which file is `@import`ing your `_base.sass`? Does it behave the way you expect when you're running SASS directly, i.e. without `gulp-watch-sass`?

**Comment by sp00m** [comment]
@kolyaraketa, any update? Are you still facing the issue?

**Comment by sp00m** [comment]
Closed because of inactivity.
