### ISSUE TITLE
Multiple import (@import "deps1", "deps2";)

### ISSUE THREAD

**Issue by MrFranke** [sp00m/gulp-watch-sass#9]
Hi! At first thanks for awesome plugin, it's saved many times for me.
But how about multiple import? It's look like a `@import "_variables", "_demo";`

**Comment by sp00m** [comment]
Hi :)

Comma separated imports are not yet handled, but I'm happy to add this feature. I'll try to work on it as soon as possible, I'll keep you posted.

In the mean time, I'm afraid you'll have to split your import into two imports:

```text
@import "_variables";
@import "_demo";
```

**Comment by sp00m** [comment]
Implemented in 1.4.0.
